# PineDocs config file.
#
# See a detailed list of all settings here:
# https://github.com/xy2z/PineDocs/tree/master#configuration


# [string] The title.
title: PineDocs

# [string] The full path of the content directory to show.
#content_dir: /data/pinedocs/content

# [string] Path to the logo inside the public/ dir.
#logo: PineDocs.png

# [string] Filename of the index file inside content_dir.
index: index.md

# [string] Theme to use.
# A theme is basically anything but the colors.
# See a list of themes in public/themes/
theme: default

# [string] The color-scheme to use.
# See available color schemes in public/color-schems/
color_scheme: pinedocs

# [string] Code highlighting themes: default, monokai, tomorrow, sunburst, darcula.
# See available themes on https://highlightjs.org/static/demo/
highlight_theme: darcula

# [bool] Use transparent bacground on code blocks?
# True: The background will be transparent.
# False: The background from the highlight_theme will be used.
code_transparent_bg: False

# [int|string] How many dirs to open on pageload.
# Use 'all' to open all dirs, or use a number to specify the levels of dir to open.
open_dirs: 0

# [bool] Render the menu footer.
render_footer: true

# [array] Exclude files. To use regex start and end with '/', like this: /regex/
exclude_files:
  - .git
  - .db

# [bool] Show file extensions.
show_file_extension: true
